version: "3"
services:
  php-apache-environment:
    container_name: php-apache
    image: php:8.0-apache
    volumes:
      - /Users/vladstroe/Projects/cart:/var/www/html/
    ports:
      - "8000:80"